// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/IBM/sarama (interfaces: SyncProducer)
//
// Generated by this command:
//
//	mockgen -destination internal/test/mocks/sarama_sync_producer.mock.go -typed -package mocks github.com/IBM/sarama SyncProducer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	sarama "github.com/IBM/sarama"
	gomock "go.uber.org/mock/gomock"
)

// MockSyncProducer is a mock of SyncProducer interface.
type MockSyncProducer struct {
	ctrl     *gomock.Controller
	recorder *MockSyncProducerMockRecorder
	isgomock struct{}
}

// MockSyncProducerMockRecorder is the mock recorder for MockSyncProducer.
type MockSyncProducerMockRecorder struct {
	mock *MockSyncProducer
}

// NewMockSyncProducer creates a new mock instance.
func NewMockSyncProducer(ctrl *gomock.Controller) *MockSyncProducer {
	mock := &MockSyncProducer{ctrl: ctrl}
	mock.recorder = &MockSyncProducerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSyncProducer) EXPECT() *MockSyncProducerMockRecorder {
	return m.recorder
}

// AbortTxn mocks base method.
func (m *MockSyncProducer) AbortTxn() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AbortTxn")
	ret0, _ := ret[0].(error)
	return ret0
}

// AbortTxn indicates an expected call of AbortTxn.
func (mr *MockSyncProducerMockRecorder) AbortTxn() *MockSyncProducerAbortTxnCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AbortTxn", reflect.TypeOf((*MockSyncProducer)(nil).AbortTxn))
	return &MockSyncProducerAbortTxnCall{Call: call}
}

// MockSyncProducerAbortTxnCall wrap *gomock.Call
type MockSyncProducerAbortTxnCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSyncProducerAbortTxnCall) Return(arg0 error) *MockSyncProducerAbortTxnCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSyncProducerAbortTxnCall) Do(f func() error) *MockSyncProducerAbortTxnCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSyncProducerAbortTxnCall) DoAndReturn(f func() error) *MockSyncProducerAbortTxnCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddMessageToTxn mocks base method.
func (m *MockSyncProducer) AddMessageToTxn(msg *sarama.ConsumerMessage, groupId string, metadata *string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMessageToTxn", msg, groupId, metadata)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMessageToTxn indicates an expected call of AddMessageToTxn.
func (mr *MockSyncProducerMockRecorder) AddMessageToTxn(msg, groupId, metadata any) *MockSyncProducerAddMessageToTxnCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMessageToTxn", reflect.TypeOf((*MockSyncProducer)(nil).AddMessageToTxn), msg, groupId, metadata)
	return &MockSyncProducerAddMessageToTxnCall{Call: call}
}

// MockSyncProducerAddMessageToTxnCall wrap *gomock.Call
type MockSyncProducerAddMessageToTxnCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSyncProducerAddMessageToTxnCall) Return(arg0 error) *MockSyncProducerAddMessageToTxnCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSyncProducerAddMessageToTxnCall) Do(f func(*sarama.ConsumerMessage, string, *string) error) *MockSyncProducerAddMessageToTxnCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSyncProducerAddMessageToTxnCall) DoAndReturn(f func(*sarama.ConsumerMessage, string, *string) error) *MockSyncProducerAddMessageToTxnCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddOffsetsToTxn mocks base method.
func (m *MockSyncProducer) AddOffsetsToTxn(offsets map[string][]*sarama.PartitionOffsetMetadata, groupId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOffsetsToTxn", offsets, groupId)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddOffsetsToTxn indicates an expected call of AddOffsetsToTxn.
func (mr *MockSyncProducerMockRecorder) AddOffsetsToTxn(offsets, groupId any) *MockSyncProducerAddOffsetsToTxnCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOffsetsToTxn", reflect.TypeOf((*MockSyncProducer)(nil).AddOffsetsToTxn), offsets, groupId)
	return &MockSyncProducerAddOffsetsToTxnCall{Call: call}
}

// MockSyncProducerAddOffsetsToTxnCall wrap *gomock.Call
type MockSyncProducerAddOffsetsToTxnCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSyncProducerAddOffsetsToTxnCall) Return(arg0 error) *MockSyncProducerAddOffsetsToTxnCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSyncProducerAddOffsetsToTxnCall) Do(f func(map[string][]*sarama.PartitionOffsetMetadata, string) error) *MockSyncProducerAddOffsetsToTxnCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSyncProducerAddOffsetsToTxnCall) DoAndReturn(f func(map[string][]*sarama.PartitionOffsetMetadata, string) error) *MockSyncProducerAddOffsetsToTxnCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// BeginTxn mocks base method.
func (m *MockSyncProducer) BeginTxn() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTxn")
	ret0, _ := ret[0].(error)
	return ret0
}

// BeginTxn indicates an expected call of BeginTxn.
func (mr *MockSyncProducerMockRecorder) BeginTxn() *MockSyncProducerBeginTxnCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTxn", reflect.TypeOf((*MockSyncProducer)(nil).BeginTxn))
	return &MockSyncProducerBeginTxnCall{Call: call}
}

// MockSyncProducerBeginTxnCall wrap *gomock.Call
type MockSyncProducerBeginTxnCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSyncProducerBeginTxnCall) Return(arg0 error) *MockSyncProducerBeginTxnCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSyncProducerBeginTxnCall) Do(f func() error) *MockSyncProducerBeginTxnCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSyncProducerBeginTxnCall) DoAndReturn(f func() error) *MockSyncProducerBeginTxnCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Close mocks base method.
func (m *MockSyncProducer) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSyncProducerMockRecorder) Close() *MockSyncProducerCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSyncProducer)(nil).Close))
	return &MockSyncProducerCloseCall{Call: call}
}

// MockSyncProducerCloseCall wrap *gomock.Call
type MockSyncProducerCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSyncProducerCloseCall) Return(arg0 error) *MockSyncProducerCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSyncProducerCloseCall) Do(f func() error) *MockSyncProducerCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSyncProducerCloseCall) DoAndReturn(f func() error) *MockSyncProducerCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// CommitTxn mocks base method.
func (m *MockSyncProducer) CommitTxn() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitTxn")
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitTxn indicates an expected call of CommitTxn.
func (mr *MockSyncProducerMockRecorder) CommitTxn() *MockSyncProducerCommitTxnCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitTxn", reflect.TypeOf((*MockSyncProducer)(nil).CommitTxn))
	return &MockSyncProducerCommitTxnCall{Call: call}
}

// MockSyncProducerCommitTxnCall wrap *gomock.Call
type MockSyncProducerCommitTxnCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSyncProducerCommitTxnCall) Return(arg0 error) *MockSyncProducerCommitTxnCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSyncProducerCommitTxnCall) Do(f func() error) *MockSyncProducerCommitTxnCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSyncProducerCommitTxnCall) DoAndReturn(f func() error) *MockSyncProducerCommitTxnCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// IsTransactional mocks base method.
func (m *MockSyncProducer) IsTransactional() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTransactional")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsTransactional indicates an expected call of IsTransactional.
func (mr *MockSyncProducerMockRecorder) IsTransactional() *MockSyncProducerIsTransactionalCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTransactional", reflect.TypeOf((*MockSyncProducer)(nil).IsTransactional))
	return &MockSyncProducerIsTransactionalCall{Call: call}
}

// MockSyncProducerIsTransactionalCall wrap *gomock.Call
type MockSyncProducerIsTransactionalCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSyncProducerIsTransactionalCall) Return(arg0 bool) *MockSyncProducerIsTransactionalCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSyncProducerIsTransactionalCall) Do(f func() bool) *MockSyncProducerIsTransactionalCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSyncProducerIsTransactionalCall) DoAndReturn(f func() bool) *MockSyncProducerIsTransactionalCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SendMessage mocks base method.
func (m *MockSyncProducer) SendMessage(msg *sarama.ProducerMessage) (int32, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", msg)
	ret0, _ := ret[0].(int32)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockSyncProducerMockRecorder) SendMessage(msg any) *MockSyncProducerSendMessageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockSyncProducer)(nil).SendMessage), msg)
	return &MockSyncProducerSendMessageCall{Call: call}
}

// MockSyncProducerSendMessageCall wrap *gomock.Call
type MockSyncProducerSendMessageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSyncProducerSendMessageCall) Return(partition int32, offset int64, err error) *MockSyncProducerSendMessageCall {
	c.Call = c.Call.Return(partition, offset, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSyncProducerSendMessageCall) Do(f func(*sarama.ProducerMessage) (int32, int64, error)) *MockSyncProducerSendMessageCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSyncProducerSendMessageCall) DoAndReturn(f func(*sarama.ProducerMessage) (int32, int64, error)) *MockSyncProducerSendMessageCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SendMessages mocks base method.
func (m *MockSyncProducer) SendMessages(msgs []*sarama.ProducerMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessages", msgs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessages indicates an expected call of SendMessages.
func (mr *MockSyncProducerMockRecorder) SendMessages(msgs any) *MockSyncProducerSendMessagesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessages", reflect.TypeOf((*MockSyncProducer)(nil).SendMessages), msgs)
	return &MockSyncProducerSendMessagesCall{Call: call}
}

// MockSyncProducerSendMessagesCall wrap *gomock.Call
type MockSyncProducerSendMessagesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSyncProducerSendMessagesCall) Return(arg0 error) *MockSyncProducerSendMessagesCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSyncProducerSendMessagesCall) Do(f func([]*sarama.ProducerMessage) error) *MockSyncProducerSendMessagesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSyncProducerSendMessagesCall) DoAndReturn(f func([]*sarama.ProducerMessage) error) *MockSyncProducerSendMessagesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// TxnStatus mocks base method.
func (m *MockSyncProducer) TxnStatus() sarama.ProducerTxnStatusFlag {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TxnStatus")
	ret0, _ := ret[0].(sarama.ProducerTxnStatusFlag)
	return ret0
}

// TxnStatus indicates an expected call of TxnStatus.
func (mr *MockSyncProducerMockRecorder) TxnStatus() *MockSyncProducerTxnStatusCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TxnStatus", reflect.TypeOf((*MockSyncProducer)(nil).TxnStatus))
	return &MockSyncProducerTxnStatusCall{Call: call}
}

// MockSyncProducerTxnStatusCall wrap *gomock.Call
type MockSyncProducerTxnStatusCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSyncProducerTxnStatusCall) Return(arg0 sarama.ProducerTxnStatusFlag) *MockSyncProducerTxnStatusCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSyncProducerTxnStatusCall) Do(f func() sarama.ProducerTxnStatusFlag) *MockSyncProducerTxnStatusCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSyncProducerTxnStatusCall) DoAndReturn(f func() sarama.ProducerTxnStatusFlag) *MockSyncProducerTxnStatusCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
